version: '3.4'

services:
  pladiasdwcexport:
    image: pladias-dwc-export
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/app
    env_file:
      - .env
